config/routes.rb
Rails.application.routes.draw do

  resources :things do
    resources :comments, only: [:create,:destroy,:update]
  end

  devise_for :users

  root 'things#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :thing
end

app/models/thing.rb
class Thing < ApplicationRecord
	belongs_to :user

	mount_uploader :photo1, PhotoUploader #carrierware
	mount_uploader :photo2, PhotoUploader #carrierware
	mount_uploader :photo3, PhotoUploader #carrierware

	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :things
  has_many :comments

  validates :firstname, presence: true, length: { minimum: 5, maximum: 50 } 
  validates :lastname, presence: true, length: { minimum: 5, maximum: 50 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :set_search_ransack
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :firstname, :lastname) }
  	devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :firstname, :lastname) }
  end

  protected
  def set_search_ransack
  	@q = Thing.ransack(params[:q])
	@things = @q.result(distinct: false).page params[:page]
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_thing
  before_action :authenticate_user!

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.new(comment_params)
    @comment.thing=@thing

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @thing, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @thing, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_thing
      @thing = Thing.find(params[:thing_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: [:show,:update,:destroy] 
  before_action :authenticate_user!, except: [:show,:index]

  # GET /things
  # GET /things.json
  def index
    @q = Thing.ransack(params[:q])
    @things = @q.result(distinct: false).page params[:page]
  end

  # GET /things/1
  # GET /things/1.json
  def show
    @thing.update(visits: @thing.visits+1)
    @comment=Comment.new
  end

  # GET /things/new
  def new
    @thing = Thing.new
  end

  # GET /things/1/edit
  def edit
    @thing = Thing.find(params[:id])
  end

  # POST /things
  # POST /things.json
  def create
    @thing = Thing.new(thing_params)
    @thing.user_id = current_user.id
    @thing.visits = 0

    respond_to do |format|
      if @thing.save
        format.html { redirect_to @thing, notice: 'Thing was successfully created.' }
        format.json { render :show, status: :created, location: @thing }
      else
        format.html { render :new }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /things/1
  # PATCH/PUT /things/1.json
  def update
    respond_to do |format|
      if @thing.update(thing_params)
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { render :show, status: :ok, location: @thing }
      else
        format.html { render :edit }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing.destroy
    respond_to do |format|
      format.html { redirect_to things_url, notice: 'Thing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_params
      params.require(:thing).permit(:name, :description, :category_id,:photo1,:photo2,:photo3)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@thing,@comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <br /><br />Escribe tu comentario<br />
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Thing</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.thing %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Thing:</strong>
  <%= @comment.thing %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CosasPerdidas</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a><%= link_to 'Cosas Perdidas', root_path, class:'navbar-brand' %></a>

        </div>

        <%= search_form_for @q do |t| %>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

          <div class="navbar-form navbar-left"><!-- Divide para ordenar (alinear al centro copiar y pegar)-->
            <div class="form-group"><!-- Divide para ordenar (alinear al centro copiar y pegar)-->
              
              <%= t.search_field :name_or_description_cont, class:"form-group" %>
            
              <%= t.select :category_id_eq, options_from_collection_for_select(Category.all, "id", "name", @q.category_id_eq), include_blank: "Todas", class:'form-group' %>

              
                <button type="submit" class="form-group">Buscar</button>
              
            </div>
          </div>

        <% end %>

          <ul class="nav navbar-nav navbar-right">

            <% if user_signed_in? %>
              <li>
              <%= link_to current_user.firstname, root_path %>
              </li>
              
              <li>
              <%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete %>
              </li>

            <% else %>
              <li>
              <%= link_to "Iniciar Sesion", new_user_session_path %>
              </li>

              <li>
              <%= link_to "Registrarse", new_user_registration_path %>
              </li>
            <%end%>
            
          </ul>

        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

  <body>
    <%= yield %>
  </body>
</html>

app/views/things/_form.html.erb
<%= form_for @thing, :html => {:multipart => true} do |f| %>

  <% if @thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
      <% @thing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  Categoria<br />
  <select name="thing[category_id]">
    <% Category.all.each do |thing| %>
      
        <option value="<%= thing.id %>"><%= thing.name %></option>
      
    <% end %>
  </select>

  <br />

    <%= f.file_field :photo1 %>
    <br />
    <%= f.file_field :photo2 %>
    <br />
    <%= f.file_field :photo3 %>


    <br />

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/things/edit.html.erb
<h1>Editing Thing</h1>

<%= render 'form', thing: @thing %>

<%= link_to 'Show', @thing %> |
<%= link_to 'Back', things_path %>

app/views/things/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Things</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Visits</th>
      <th>User</th>
      <th>Imagen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @things.each do |thing| %>
      <tr>
        <td><%= link_to thing.name, thing %></td>
        <td><%= thing.description %></td>
        <td><%= thing.visits %></td>
        <td><%= thing.user.email %></td>
        <td><%= image_tag(thing.photo1_url, :width => 65, :height => 75) if thing.photo1.present? %></td>
        <td><%= link_to 'Show', thing %></td>
        <td><%= link_to 'Edit', edit_thing_path(thing) %></td>
        <td><%= link_to 'Destroy', thing, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @things %>

<br>

<%= link_to 'New Thing', new_thing_path, class: 'waves-effect waves-light btn' %>

app/views/things/new.html.erb
<h1>New Thing</h1>

<%= render 'form', thing: @thing %>

<%= link_to 'Back', things_path %>

app/views/things/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @thing.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @thing.description %>
</p>

<p>
  <strong>Visits:</strong>
  <%= @thing.visits %>
</p>

<p>
  <strong>User:</strong>
  <%= @thing.user.email %>
</p>

<p>
  <strong>Categoria:</strong>
  <% Category.all.each do |cat| %>
      <% if cat.id == @thing.category_id then %>
      		<%= cat.name %>
      <% end %>
    <% end %>
</p>

<br />
<%= image_tag(@thing.photo1_url, :width => 170, :height => 190) if @thing.photo1.present? %>

<%= image_tag(@thing.photo2_url, :width => 170, :height => 190) if @thing.photo2.present? %>

<%= image_tag(@thing.photo3_url, :width => 170, :height => 190) if @thing.photo3.present? %>
<br />

<h2>Comentarios</h2>

<% @thing.comments.each do |comment| %>
    <h3><%= comment.body %></h3><%= comment.user.email %><br />
    <% if current_user.id == comment.user_id %>
    <%= link_to "Eliminar",  [comment.thing, comment], method: :delete %>
    <% end %>
<% end %>

<%= render "comments/form" %>
<br />

<%= link_to 'Edit', edit_thing_path(@thing) %> |
<%= link_to 'Back', things_path %>